linters:
  enable:
    - goheader
    - golint
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[2-9]\d
    template-path: code-header-template.txt