apiVersion: v1
kind: Secret
metadata:
  name: http-auth
data:
  # Configured in e2e tests
  username: admin
  password: password
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: .
    http:
      # Configured in e2e tests
      url: http://localhost:8100/NOTICE
      secretRef:
        name: http-auth
