apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: custom-repo-custom-version
    helmChart:
      name: contour
      version: 7.10.1
      repository:
        url: oci://REPLACE_ME_REGISTRY_ADDR/helmcharts