apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: exact-sha
    hg:
      url: http://hg.code.sf.net/p/carvel-sample-hg-repo/sample
      ref: dc860d1ce57c
    includePaths:
    - concourse-overlay/*

  - path: tag
    hg:
      url: http://hg.code.sf.net/p/carvel-sample-hg-repo/sample
      ref: 0.1.1
    includePaths:
    - data-values/*
